export type CatalogSkuSeed = {
  sku: string;
  sourceCategory: string;
  name: string;
  color: string;
  unit: string;
};

// Imported from Freshphool_SKU-V1.xlsx. Each SKU code appears once.
export const catalogSkus: CatalogSkuSeed[] = [
  ["FP-ANTHURIUM-RED", "Decorative Flowers", "Anthurium", "Red", "Stem"],
  ["FP-ASI-LIL-ORG", "Decorative Flowers", "Asiatic Lily", "Orange", "Stem"],
  ["FP-ASI-LIL-PNK", "Decorative Flowers", "Asiatic Lily", "Pink", "Stem"],
  ["FP-ASI-LIL-WHT", "Decorative Flowers", "Asiatic Lily", "White", "Stem"],
  ["FP-ASI-LIL-YEL", "Decorative Flowers", "Asiatic Lily", "Yellow", "Stem"],
  ["FP-BABY-BREATH-PUR", "Decorative Flowers", "Baby's Breath", "Purple", "Small/Medium/Large Bunch"],
  ["FP-BABY'S-BREATH-WHITE", "Decorative Flowers", "Baby's Breath", "White", "Small/Medium/Large Bunch"],
  ["FP-CARNATION-PEACH", "Decorative Flowers", "Carnation", "Peach", "Stem"],
  ["FP-CARNATION-PINK", "Decorative Flowers", "Carnation", "Pink", "Stem"],
  ["FP-CARNATION-PURPLE", "Decorative Flowers", "Carnation", "Purple", "Stem"],
  ["FP-CARNATION-RED", "Decorative Flowers", "Carnation", "Red", "Stem"],
  ["FP-CARNATION-WHITE", "Decorative Flowers", "Carnation", "White", "Stem"],
  ["FP-CARNATION-ORANGE", "Decorative Flowers", "Carnation", "Orange", "Stem"],
  ["FP-CARNATION-YELLOW", "Decorative Flowers", "Carnation", "Yellow", "Stem"],
  ["FP-CHRYSANTHEMUM-RED", "Decorative Flowers", "Chrysanthemum", "Red", "Stem"],
  ["FP-CHRYSANTHEMUM-PINK", "Decorative Flowers", "Chrysanthemum", "Pink", "Stem"],
  ["FP-CHRYSANTHEMUM-PURPLE", "Decorative Flowers", "Chrysanthemum", "Purple", "Stem"],
  ["FP-CHRYSANTHEMUM-WHITE", "Decorative Flowers", "Chrysanthemum", "White", "Stem"],
  ["FP-CHRYSANTHEMUM-YELLOW", "Decorative Flowers", "Chrysanthemum", "Yellow", "Stem"],
  ["FP-GERBERA-ORANGE", "Decorative Flowers", "Gerbera", "Orange", "Stem"],
  ["FP-GERBERA-PINK", "Decorative Flowers", "Gerbera", "Pink", "Stem"],
  ["FP-GERBERA-PURPLE", "Decorative Flowers", "Gerbera", "Purple", "Stem"],
  ["FP-GERBERA-SALMON", "Decorative Flowers", "Gerbera", "Salmon", "Stem"],
  ["FP-GERBERA-RED", "Decorative Flowers", "Gerbera", "Red", "Stem"],
  ["FP-GERBERA-WHITE", "Decorative Flowers", "Gerbera", "White", "Stem"],
  ["FP-GERBERA-YELLOW", "Decorative Flowers", "Gerbera", "Yellow", "Stem"],
  ["FP-GLADIOLUS-PINK", "Decorative Flowers", "Gladiolus", "Pink", "Stem"],
  ["FP-GLADIOLUS-RED", "Decorative Flowers", "Gladiolus", "Red", "Stem"],
  ["FP-GLADIOLUS-WHITE", "Decorative Flowers", "Gladiolus", "White", "Stem"],
  ["FP-GLADIOLUS-YELLOW", "Decorative Flowers", "Gladiolus", "Yellow", "Stem"],
  ["FP-ORCHID-BLUE", "Decorative Flowers", "Orchid", "Blue", "Stem"],
  ["FP-ORI-LIL-PNK", "Decorative Flowers", "Oriental Lily", "Pink", "Stem"],
  ["FP-ORI-LIL-WHT", "Decorative Flowers", "Oriental Lily", "White", "Stem"],
  ["FP-ROSE-LAVENDER", "Decorative Flowers", "Rose", "Lavender", "Stem"],
  ["FP-ROSE-ORANGE", "Decorative Flowers", "Rose", "Orange", "Stem"],
  ["FP-ROSE-PEACH", "Decorative Flowers", "Rose", "Peach", "Stem"],
  ["FP-ROSE-PINK", "Decorative Flowers", "Rose", "Pink", "Stem"],
  ["FP-ROSE-RED", "Decorative Flowers", "Rose", "Red", "Stem"],
  ["FP-ROSE-WHITE", "Decorative Flowers", "Rose", "White", "Stem"],
  ["FP-ROSE-YELLOW", "Decorative Flowers", "Rose", "Yellow", "Stem"],
  ["FP-SUNFLOWER-YELLOW", "Decorative Flowers", "Sunflower", "Yellow", "Stem"],
  ["FP-TUBEROSE-WHITE", "Decorative Flowers", "Tuberose", "White", "Stem"],
  ["FP-DAHLIAS-RED", "Decorative Flowers", "Dahlias", "Red", "Stem"],
  ["FP-DAHLIAS-WHITE", "Decorative Flowers", "Dahlias", "White", "Stem"],
  ["FP-DAHLIAS-ORANGE", "Decorative Flowers", "Dahlias", "Yellow", "Stem"],
  ["FP-ASPARAGUS-FERN-GREEN", "Greenery & Fillers", "Asparagus Fern", "Green", "Stem"],
  ["FP-EUCALYPTUS-GREEN", "Greenery & Fillers", "Eucalyptus", "Green", "Stem"],
  ["FP-BILWA-LEAVES-100G", "Puja Flowers", "Bilwa Leaves", "Green", "100 g"],
  ["FP-BILWA-LEAVES-250G", "Puja Flowers", "Bilwa Leaves", "Green", "250 g"],
  ["FP-DURVA-GRASS", "Puja Flowers", "Durva Grass", "Green", "Tied Bunch"],
  ["FP-JASMINE-/-MALLIG-WHITE", "Puja Flowers", "Jasmine / Mallige", "White", "50 g"],
  ["FP-KANAKAMBARAM-ORANGE", "Puja Flowers", "Kanakambaram", "Orange", "50 g"],
  ["FP-LOOSE-LILY-100G", "Puja Flowers", "Loose Lily Flowers", "Mixed", "100 g"],
  ["FP-LOOSE-LILY-250G", "Puja Flowers", "Loose Lily Flowers", "Mixed", "250 g"],
  ["FP-LOOSE-TULSI-100G", "Puja Flowers", "Loose Tulsi Leaves", "Green", "100 g"],
  ["FP-LOOSE-TULSI-250G", "Puja Flowers", "Loose Tulsi Leaves", "Green", "250 g"],
  ["FP-LOTUS-PINK", "Puja Flowers", "Lotus", "Pink", "1 pc"],
  ["FP-LOTUS-WHITE", "Puja Flowers", "Lotus", "White", "1 pc"],
  ["FP-MARIGOLD-MIXED-YELL", "Puja Flowers", "Marigold", "Mixed Yellow & Orange", "100 g"],
  ["FP-MARIGOLD-ORANGE", "Puja Flowers", "Marigold", "Orange", "100 g"],
  ["FP-MARIGOLD-YELLOW", "Puja Flowers", "Marigold", "Yellow", "100 g"],
  ["FP-SEVANTHI-PINK", "Puja Flowers", "Sevanthi", "Pink", "100 g"],
  ["FP-SEVANTHI-WHITE", "Puja Flowers", "Sevanthi", "White", "100 g"],
  ["FP-SEVANTHI-YELLOW", "Puja Flowers", "Sevanthi", "Yellow", "100 g"],
  ["FP-TULSI-GARLAND", "Puja Flowers", "Tulsi Garland", "Green", "Garland"],
  ["FP-PUJA-FLOWERS-DAI-MIXED", "Puja Packs", "Puja Flowers Daily Pack", "Mixed", "Pack"],
  ["FP-PUJA-FLOWERS-PRE-MIXED", "Puja Packs", "Puja Flowers Premium Pack", "Mixed", "Pack"],
  ["FP-JASMINE-GARLAND-WHITE", "Garlands", "Jasmine Garland", "White", "Garland"],
  ["FP-MARIGOLD-GARLAND-MIXED", "Garlands", "Marigold Garland", "Mixed", "Garland"],
  ["FP-MARIGOLD-GARLAND-ORANGE", "Garlands", "Marigold Garland", "Orange", "Garland"],
  ["FP-MARIGOLD-GARLAND-YELLOW", "Garlands", "Marigold Garland", "Yellow", "Garland"],
  ["FP-MIXED-PUJA-GARLA-MIXED", "Garlands", "Mixed Puja Garland", "Mixed", "Garland"],
  ["FP-ROSE-GARLAND-MIXED", "Garlands", "Rose Garland", "Mixed", "Garland"],
  ["FP-ROSE-GARLAND-RED", "Garlands", "Rose Garland", "Red", "Garland"],
  ["FP-TUBEROSE-GARLAND-WHITE", "Garlands", "Tuberose Garland", "White", "Garland"],
].map(([sku, sourceCategory, name, color, unit]) => ({ sku, sourceCategory, name, color, unit }));
